// Generated by prepare_unmasked.py. Do not edit by hand.
window.UNMASKED = {
 "pages": 303,
 "tokens": 713059,
 "dot": 10,
 "words": {
  "man": {
   "total": 3545,
   "real": 224,
   "name": 3310,
   "other": 11,
   "parts": [
    {
     "label": "real",
     "count": 224
    },
    {
     "label": "Spider-Man",
     "count": 1932
    },
    {
     "label": "Iron Man",
     "count": 401
    },
    {
     "label": "Man-Thing",
     "count": 167
    },
    {
     "label": "Power Man",
     "count": 81
    },
    {
     "label": "other names",
     "count": 729
    },
    {
     "label": "other caps",
     "count": 11
    }
   ],
   "dots": [
    {
     "label": "real",
     "n": 22
    },
    {
     "label": "Spider-Man",
     "n": 193
    },
    {
     "label": "Iron Man",
     "n": 40
    },
    {
     "label": "Man-Thing",
     "n": 17
    },
    {
     "label": "Power Man",
     "n": 8
    },
    {
     "label": "other names",
     "n": 73
    },
    {
     "label": "other caps",
     "n": 1
    }
   ],
   "examples": {
    "Spider-Man": [
     {
      "page": "Abomination (character)",
      "left": "…more. The process drives Blonsky insane, and he battles heroes Spider-",
      "match": "Man",
      "right": " and the She-Hulk, managing to knock both unconscious. The Abomination…"
     },
     {
      "page": "Anne Weying",
      "left": "…other media Film Anne Weying appears in films set in Sony's Spider-",
      "match": "Man",
      "right": " Universe, portrayed by Michelle Williams. First appearing in Venom (…"
     },
     {
      "page": "Anya Corazon",
      "left": "…caped. Spider-Man/Araña: The Hunter Revealed In the one-shot Spider-",
      "match": "Man",
      "right": "/Araña: the Hunter Revealed, she discovers that her exoskeleton is not…"
     },
     {
      "page": "Anya Corazon",
      "left": "…Spider-powered people (consisting of Spider-Woman, Spider-Ham, Spider-",
      "match": "Man",
      "right": " Noir, and Spider-Man of India), neither of whom remembered their prev…"
     }
    ],
    "Iron Man": [
     {
      "page": "Abomination (character)",
      "left": "…defeats the Abomination yet again with the aid of the Avengers. Iron ",
      "match": "Man",
      "right": " uses technology taken from the Order of the Shield to teleport the Ab…"
     },
     {
      "page": "Bill Foster (character)",
      "left": "…narok, a clone of Thor. Foster is buried in his giant form, with Iron ",
      "match": "Man",
      "right": " paying for the thirty-eight burial plots required to accommodate his…"
     },
     {
      "page": "Black Knight (Marvel Comics)",
      "left": "…c. The Nathan Garrett incarnation of the Black Knight appears in Iron ",
      "match": "Man",
      "right": ": Armored Adventures, voiced by Alistair Abell. This version is a Magg…"
     },
     {
      "page": "Black Widow (Natasha Romanova)",
      "left": "…y known to the public after the character was adapted to film in Iron ",
      "match": "Man",
      "right": " 2 (2010). The film's emphasis on her as a spy instead of a superhero…"
     }
    ],
    "Man-Thing": [
     {
      "page": "Adam Warlock",
      "left": "…nation of Iron Man and Thor), Man-Thing-Thang-Thoom (a combination of ",
      "match": "Man",
      "right": "-Thing and Fin Fang Foom), Moon Squirrel (a combination of Moon Girl a…"
     },
     {
      "page": "Man-Thing",
      "left": "The ",
      "match": "Man",
      "right": "-Thing (Dr. Theodore \"Ted\" Sallis) is a fictional character appearing…"
     },
     {
      "page": "Man-Thing",
      "left": "…nted 1950s horror/fantasy stories. Steve Gerber, who would become the ",
      "match": "Man",
      "right": "-Thing's signature writer, succeeded Conway the following issue, with…"
     },
     {
      "page": "Man-Thing",
      "left": "…them to a resolution for his own War is Hell series. Black and white ",
      "match": "Man",
      "right": "-Thing stories, and some color covers, also appeared in the Marvel mag…"
     }
    ],
    "real": [
     {
      "page": "Agent X (Marvel Comics)",
      "left": "…es. Black Swan proposes a three-way psychic operation to restore each ",
      "match": "man",
      "right": " to their correct personal states, but double-crosses them. Outlaw ret…"
     },
     {
      "page": "Black Marvel",
      "left": "…ith a touch. He helped expose that it was all a hoax created by a con ",
      "match": "man",
      "right": " named Ridley and his accomplice Baku, the local witch doctor who pose…"
     },
     {
      "page": "Blade (character)",
      "left": "…r vampires that he and Afari found in abundance. Over time, the young ",
      "match": "man",
      "right": " became an Olympic-level athlete and a formidable hand-to-hand combata…"
     },
     {
      "page": "Chase Stein",
      "left": "…an claiming to be his paternal uncle Hunter Stein. Chase believes the ",
      "match": "man",
      "right": " is lying because he remembers killing his uncle and driving off. Not…"
     }
    ],
    "Power Man": [
     {
      "page": "Alex Wilder",
      "left": "…the villainous team Young Masters. Alex reappears in the series Power ",
      "match": "Man",
      "right": " and Iron Fist, where he spreads a demonic drug called Redemption. P…"
     },
     {
      "page": "Iron Fist (character)",
      "left": "…e's series Power Man #48–50. The title of the series changed to Power ",
      "match": "Man",
      "right": " and Iron Fist with issue #50 (April 1978), although the indicia did n…"
     },
     {
      "page": "Jessica Jones",
      "left": "…changes her codename to Power Woman to both honor her husband, Power ",
      "match": "Man",
      "right": " (Luke Cage) and because she considers it a more inspiring choice for…"
     },
     {
      "page": "Luke Cage",
      "left": "…fore returning them to more mundane environments. 1980s–1990s Power ",
      "match": "Man",
      "right": " and Iron Fist received its long-term artist when Kerry Gammill was ad…"
     }
    ]
   }
  },
  "woman": {
   "total": 479,
   "real": 121,
   "name": 358,
   "other": 0,
   "parts": [
    {
     "label": "real",
     "count": 121
    },
    {
     "label": "Spider-Woman",
     "count": 321
    },
    {
     "label": "Invisible Woman",
     "count": 19
    },
    {
     "label": "Wonder Woman",
     "count": 6
    },
    {
     "label": "Warrior Woman",
     "count": 5
    },
    {
     "label": "other names",
     "count": 7
    }
   ],
   "dots": [
    {
     "label": "real",
     "n": 12
    },
    {
     "label": "Spider-Woman",
     "n": 32
    },
    {
     "label": "Invisible Woman",
     "n": 2
    },
    {
     "label": "Wonder Woman",
     "n": 1
    },
    {
     "label": "Warrior Woman",
     "n": 0
    },
    {
     "label": "other names",
     "n": 1
    }
   ],
   "examples": {
    "real": [
     {
      "page": "Abomination (character)",
      "left": "…Hulk persuades the Abomination to free his wife. After befriending a ",
      "match": "woman",
      "right": " who finds her way into the sewers, the Abomination battles Namor duri…"
     },
     {
      "page": "Black Panther (character)",
      "left": "…ving birth to her first child, T'Challa; from the relationship with a ",
      "match": "woman",
      "right": " of another tribe T'Chaka then has a second son, Jakarra, and finally…"
     },
     {
      "page": "Deadpool",
      "left": "…wo former lovers in Hell. The new Deadpool is also being pursued by a ",
      "match": "woman",
      "right": " who wears a costume that looks like Wade's Zenpool identity. The myst…"
     },
     {
      "page": "Franklin Richards (character)",
      "left": "…n Fantastic Four Annual (1998). This version is married to a Wakandan ",
      "match": "woman",
      "right": " named Zawadi and has a daughter named N'Yami. Franklin is also a memb…"
     }
    ],
    "Invisible Woman": [
     {
      "page": "Adam Warlock",
      "left": "…ers Mister Invisible (a combination of Mister Fantastic and Invisible ",
      "match": "Woman",
      "right": ") and Hot Rocks (a combination of Human Torch and Thing) as well as a…"
     },
     {
      "page": "Captain Universe",
      "left": "…Universe/Daredevil, Captain Universe/X-23, Captain Universe/Invisible ",
      "match": "Woman",
      "right": " and Captain Universe/Silver Surfer. The Uni-Power made a brief appear…"
     },
     {
      "page": "Human Torch",
      "left": "…aster. To help the Thing cope with Mister Fantastic and the Invisible ",
      "match": "Woman",
      "right": "'s disappearance, the Human Torch takes him on a journey through the M…"
     },
     {
      "page": "Shamrock (comics)",
      "left": "…ron Man, Vanguard, Iron Fist, Storm, Arabian Knight, Sabra, Invisible ",
      "match": "Woman",
      "right": ", Angel, Black Panther, Sunfire, and the Collective Man. When the Gran…"
     }
    ],
    "Spider-Woman": [
     {
      "page": "Anya Corazon",
      "left": "…g the \"Spider-Verse\" storyline, Spider-Girl joined Spider-Man, Spider-",
      "match": "Woman",
      "right": " and other spider totems from all over the multiverse to fight the Inh…"
     },
     {
      "page": "Darkdevil",
      "left": "…Spider-Man of Earth-3145) on helping Spider-Girl (now known as Spider-",
      "match": "Woman",
      "right": ") stopping Hope Pym/Red Queen and Entralla by freeing the mind-control…"
     },
     {
      "page": "Hornet (comics)",
      "left": "…s had given him powers for the sole purpose of having him kill Spider-",
      "match": "Woman",
      "right": ". Spider-Woman purges the formula from Scotty's bloodstream, stripping…"
     },
     {
      "page": "Human Fly (character)",
      "left": "…ew, who was mutated in a lab accident. Hagel manages to deduce Spider-",
      "match": "Woman",
      "right": "'s secret identity, but forgets it after being returned to normal. An…"
     }
    ],
    "Warrior Woman": [
     {
      "page": "Elsa Bloodstone",
      "left": "…roster consisted of Valkyrie, Misty Knight, Annabelle Riggs, Warrior ",
      "match": "Woman",
      "right": ", Danielle Moonstar and Clea. The following year, she was part of the…"
     },
     {
      "page": "Human Torch (android)",
      "left": "…ved her life and restored her youth. A similar transfusion to Warrior ",
      "match": "Woman",
      "right": " reversed much of her brain damage and restored her health and power.…"
     },
     {
      "page": "Spitfire (character)",
      "left": "…o be executed when she was rescued by Union Jack. She battled Warrior ",
      "match": "Woman",
      "right": ", and escaped from Germany with the Invaders. With the Invaders, she f…"
     },
     {
      "page": "Spitfire (character)",
      "left": "…in a mission to rescue Namor from the original Master Man and Warrior ",
      "match": "Woman",
      "right": ", during which she was shot. She received another life-saving blood tr…"
     }
    ],
    "Wonder Woman": [
     {
      "page": "Misty Knight",
      "left": "…DC had previously introduced Nubia, a supporting character for Wonder ",
      "match": "Woman",
      "right": ", in 1973. In Marvel Comics, preceding characters were Gabe Jones (deb…"
     },
     {
      "page": "She-Hulk",
      "left": "…ing the final battle against Krona and his forces, she assists Wonder ",
      "match": "Woman",
      "right": " in her battle against Surtur, and eventually appears at the end as on…"
     },
     {
      "page": "Spider-Woman",
      "left": "…ought out Wonder Man, and [DC Comics] sued us because they had Wonder ",
      "match": "Woman",
      "right": ", and ... I said okay, I'll discontinue Wonder Man. And all of a sudde…"
     },
     {
      "page": "Spider-Woman (Jessica Drew)",
      "left": "…ought out Wonder Man, and [DC Comics] sued us because they had Wonder ",
      "match": "Woman",
      "right": ", and... I said okay, I'll discontinue Wonder Man. And all of a sudden…"
     }
    ]
   }
  },
  "men": {
   "total": 1630,
   "real": 76,
   "name": 1551,
   "other": 3,
   "parts": [
    {
     "label": "real",
     "count": 76
    },
    {
     "label": "X-Men",
     "count": 1500
    },
    {
     "label": "Spider-Men",
     "count": 15
    },
    {
     "label": "That Men",
     "count": 7
    },
    {
     "label": "Young Men",
     "count": 6
    },
    {
     "label": "other names",
     "count": 23
    },
    {
     "label": "other caps",
     "count": 3
    }
   ],
   "dots": [
    {
     "label": "real",
     "n": 8
    },
    {
     "label": "X-Men",
     "n": 150
    },
    {
     "label": "Spider-Men",
     "n": 1
    },
    {
     "label": "That Men",
     "n": 1
    },
    {
     "label": "Young Men",
     "n": 1
    },
    {
     "label": "other names",
     "n": 2
    },
    {
     "label": "other caps",
     "n": 0
    }
   ],
   "examples": {
    "X-Men": [
     {
      "page": "Agent X (Marvel Comics)",
      "left": "…th an X in the title to more closely identify it with their popular X-",
      "match": "Men",
      "right": " franchise. As part of the same effort, Cable was changed to Soldier X…"
     },
     {
      "page": "Anole (character)",
      "left": "…Yost and Kyle felt adding Anole and the character Pixie to the New X-",
      "match": "Men",
      "right": " team gave the roster \"tonal balance\" and the opportunity to slightly…"
     },
     {
      "page": "Anole (character)",
      "left": "…events such as X-Men: Manifest Destiny, Secret Invasion: X-Men, and X-",
      "match": "Men",
      "right": ": Nation X. Anole was featured in the story \"Good Judy\", published as…"
     },
     {
      "page": "Anole (character)",
      "left": "…is and that his problems come from Northstar, along with the other X-",
      "match": "Men",
      "right": ", for providing the students under their care with a poor education, s…"
     }
    ],
    "real": [
     {
      "page": "Ajak",
      "left": "…self into suspended animation along with his assistants. Ajak and his ",
      "match": "men",
      "right": " are awakened by fellow Eternal Ikaris in time to greet the Fourth Hos…"
     },
     {
      "page": "Black Widow (Natasha Romanova)",
      "left": "…er 20th-century appearances, Black Widow was primarily defined by the ",
      "match": "men",
      "right": " around her. When she was a villain, Black Widow's motivation was to h…"
     },
     {
      "page": "Ghost Rider",
      "left": "…'s family. Parham meets a horse-riding Ghost Rider who seeks the same ",
      "match": "men",
      "right": ". Eventually, Parham learns about the deaths instrumental in helping s…"
     },
     {
      "page": "Jack Monroe (character)",
      "left": "…e himself up to the Commission, Nomad refuses to help him and the two ",
      "match": "men",
      "right": " part on bad terms. Going solo again, Monroe becomes an urban vigilant…"
     }
    ],
    "That Men": [
     {
      "page": "Black Cat (Marvel Comics)",
      "left": "…tor Kevin Smith began writing the Spider-Man/Black Cat: The Evil That ",
      "match": "Men",
      "right": " Do miniseries in 2002. After the third issue the series went on a hia…"
     },
     {
      "page": "Black Cat (Marvel Comics)",
      "left": "…ist. Literary reception Volumes Spider-Man/Black Cat: Evil That ",
      "match": "Men",
      "right": " Do (2002) According to Diamond Comic Distributors, Spider-Man/Black C…"
     },
     {
      "page": "Black Cat (Marvel Comics)",
      "left": "…selling comic book in June 2002. Spider-Man/Black Cat: The Evil That ",
      "match": "Men",
      "right": " Do #1 was the 14th best selling comic book in 2002. Shawn S. Lealos o…"
     },
     {
      "page": "Black Cat (Marvel Comics)",
      "left": "…e came with Marvel Comics' series Spider-Man/Black Cat: The Evil That ",
      "match": "Men",
      "right": " Do. The controversy here was part of the Women in Fridges concept, as…"
     }
    ],
    "Spider-Men": [
     {
      "page": "Captain Universe",
      "left": "…ite Event is coming. During the \"Spider-Geddon\" storyline, the Spider-",
      "match": "Men",
      "right": " summoned the Enigma Force to aid them in their fight. The Enigma Forc…"
     },
     {
      "page": "Gwenpool",
      "left": "…nce in the alternate universe of Peter Parker & Miles Morales: Spider-",
      "match": "Men",
      "right": " Double Trouble, attending a villain convention with Batroc the Leaper…"
     },
     {
      "page": "Spider-Man (Marvel Mangaverse)",
      "left": "…der-Man. He is just one of many examples of different cultural Spider-",
      "match": "Men",
      "right": " much like Spider-Man (Pavitr Prabhakar), Spider-Man 2099, and Miles M…"
     },
     {
      "page": "Spider-UK",
      "left": "…tes he wants to help them. This causes Spider-UK and the other Spider-",
      "match": "Men",
      "right": " to linger around Oscorp for a while. Spider-UK and the other Spider-M…"
     }
    ],
    "Young Men": [
     {
      "page": "Human Torch (android)",
      "left": "…Comics—attempted to revive superheroes with the anthology comic Young ",
      "match": "Men",
      "right": " #24–28 (Dec. 1953 – June 1954), starring the Human Torch (art by Syd…"
     },
     {
      "page": "Jack Monroe (character)",
      "left": "…s. This complicated origin is the reason that some sources list Young ",
      "match": "Men",
      "right": " #24 (December 1953; the first appearance of the communist-hunting Cap…"
     },
     {
      "page": "William Burnside (character)",
      "left": "…e for Marvel Comics. Captain America and Bucky were depicted in Young ",
      "match": "Men",
      "right": " during the 1950s, but later official Marvel continuity established in…"
     },
     {
      "page": "William Burnside (character)",
      "left": "…1941 until 1949. He was then revived unsuccessfully in 1953 in Young ",
      "match": "Men",
      "right": " #24–28 (Dec. 1953– May 1954) by Stan Lee with Mort Lawrence and John…"
     }
    ]
   }
  },
  "women": {
   "total": 100,
   "real": 53,
   "name": 33,
   "other": 14,
   "parts": [
    {
     "label": "real",
     "count": 53
    },
    {
     "label": "Spider-Women",
     "count": 20
    },
    {
     "label": "Sexiest Women",
     "count": 4
    },
    {
     "label": "The Women",
     "count": 2
    },
    {
     "label": "Awesome Women",
     "count": 2
    },
    {
     "label": "other names",
     "count": 5
    },
    {
     "label": "other caps",
     "count": 14
    }
   ],
   "dots": [
    {
     "label": "real",
     "n": 5
    },
    {
     "label": "Spider-Women",
     "n": 2
    },
    {
     "label": "Sexiest Women",
     "n": 1
    },
    {
     "label": "The Women",
     "n": 0
    },
    {
     "label": "Awesome Women",
     "n": 0
    },
    {
     "label": "other names",
     "n": 1
    },
    {
     "label": "other caps",
     "n": 1
    }
   ],
   "examples": {
    "real": [
     {
      "page": "Betsy Braddock",
      "left": "…acter Kwannon. Following nearly 30 years of publication history, both ",
      "match": "women",
      "right": " were returned to their original bodies, and Betsy took up the mantle…"
     },
     {
      "page": "Emma Frost",
      "left": "…heir own ranks. However, the process was soon reversed, restoring the ",
      "match": "women",
      "right": " to their respective bodies. Later, Frost was rendered comatose tempor…"
     },
     {
      "page": "Jubilee (character)",
      "left": "…X-Men members Dazzler, Psylocke, Rogue, and Storm. Curious about the ",
      "match": "women",
      "right": ", she tracked them to the portal leading back to their base in the Out…"
     },
     {
      "page": "Scarlet Witch",
      "left": "…s formed by Amora the Enchantress who uses her magic to influence the ",
      "match": "women",
      "right": " members of the Avengers into turning against their male teammates. Wa…"
     }
    ],
    "Sexiest Women": [
     {
      "page": "Emma Frost",
      "left": "…ist. Comics Buyer's Guide ranked Emma Frost 5th in their \"100 Sexiest ",
      "match": "Women",
      "right": " in Comics\" list. Anthony Orlando of Digital Trends ranked Emma Frost…"
     },
     {
      "page": "Jean Grey",
      "left": "…list. Comics Buyer's Guide ranked Jean Grey 3rd in their \"100 Sexiest ",
      "match": "Women",
      "right": " in Comics\" list. Joshua Corvington of Sportskeeda ranked Jean Grey 6t…"
     },
     {
      "page": "She-Hulk",
      "left": "…list. Comics Buyer's Guide ranked She-Hulk 11th in their \"100 Sexiest ",
      "match": "Women",
      "right": " in Comics\" list. Wizard ranked She-Hulk 104th in their \"200 comic boo…"
     },
     {
      "page": "Spider-Woman (Jessica Drew)",
      "left": "…, Comics Buyer's Guide ranked Jessica Drew 54th in their \"100 Sexiest ",
      "match": "Women",
      "right": " in Comics\" list. In 2012, IGN ranked Jessica Drew 20th in their \"Top…"
     }
    ],
    "The Women": [
     {
      "page": "Firebird (Marvel Comics)",
      "left": "…al) La Espirita at the Comic Book DB (archived from the original) The ",
      "match": "Women",
      "right": " of Marvel Comics Firebird Page…"
     },
     {
      "page": "Jean Grey",
      "left": "…d by writers as Xavier 'sharing' some of his telepathy with her. The ",
      "match": "Women",
      "right": " of Marvel: Celebrating Seven Decades Handbook detailed Jean's telepat…"
     }
    ],
    "Awesome Women": [
     {
      "page": "Jessica Jones",
      "left": "…cs\" list. In 2022, Nerdist included Jessica Jones in their \"8 Awesome ",
      "match": "Women",
      "right": " Detectives in Comics\" list. In 2022, CBR.com ranked Jessica Jones and…"
     },
     {
      "page": "Misty Knight",
      "left": "…er. Rosie Knight of Nerdist included Misty Knight in their \"8 Awesome ",
      "match": "Women",
      "right": " Detectives in Comics\" list. John Wilson of WhatCulture ranked Misty K…"
     }
    ],
    "Spider-Women": [
     {
      "page": "Mayday Parker",
      "left": "…acked a nearby building in an attempt to steal silver, the two Spider-",
      "match": "Women",
      "right": " jumped into action, only for Gwen to get captured when Mayday attempt…"
     },
     {
      "page": "Spider-Bitch (Ashley Barton)",
      "left": "…ell to be dressed in a costume similar to that of the deceased Spider-",
      "match": "Women",
      "right": " and her aunt Mayday Parker / Spider-Girl. Surprised, having \"never re…"
     },
     {
      "page": "Spider-Woman (Gwen Stacy)",
      "left": "…-Women. It commenced with Spider-Women Alpha #1 and ended with Spider-",
      "match": "Women",
      "right": " Omega #1, with certain issues of Spider-Woman, Silk and Spider-Gwen p…"
     },
     {
      "page": "Spider-Woman (Jessica Drew)",
      "left": "…Spider-Woman, Gwen Stacy and Silk were the protagonists of the Spider-",
      "match": "Women",
      "right": " event. Spider-Woman issues #6 and #7 were the tie-ins. The ongoing wa…"
     }
    ]
   }
  },
  "boy": {
   "total": 172,
   "real": 53,
   "name": 119,
   "other": 0,
   "parts": [
    {
     "label": "real",
     "count": 53
    },
    {
     "label": "Marvel Boy",
     "count": 55
    },
    {
     "label": "Moon-Boy",
     "count": 27
    },
    {
     "label": "Spider-Boy",
     "count": 20
    },
    {
     "label": "Boy-Thing",
     "count": 4
    },
    {
     "label": "other names",
     "count": 13
    }
   ],
   "dots": [
    {
     "label": "real",
     "n": 5
    },
    {
     "label": "Marvel Boy",
     "n": 6
    },
    {
     "label": "Moon-Boy",
     "n": 3
    },
    {
     "label": "Spider-Boy",
     "n": 2
    },
    {
     "label": "Boy-Thing",
     "n": 0
    },
    {
     "label": "other names",
     "n": 1
    }
   ],
   "examples": {
    "real": [
     {
      "page": "Abomination (character)",
      "left": "…ht the She-Hulk. Teen Abomination Teen Abomination is a 13-year-old ",
      "match": "boy",
      "right": " who was exposed to gamma radiation and became a teenage version of th…"
     },
     {
      "page": "Devil Dinosaur",
      "left": "…rolled in her school, Moon Girl briefly transforms Devil into a human ",
      "match": "boy",
      "right": " and enrolls him in her class to tone down his destructive accidents.…"
     },
     {
      "page": "Human Torch (android)",
      "left": "…his powers both much stronger and more unstable. To keep Toro a young ",
      "match": "boy",
      "right": ", the writers retconned the character slightly, claiming the Torch met…"
     },
     {
      "page": "Morbius",
      "left": "…and fatal blood condition. His only true friend during this time is a ",
      "match": "boy",
      "right": " named Emil Nikos who, like him, is interested in medicine and science…"
     }
    ],
    "Spider-Boy": [
     {
      "page": "Anya Corazon",
      "left": "…truck by the totem dagger, which also revived the then-unknown Spider-",
      "match": "Boy",
      "right": ". Spider-Boy later visits Anya in an attempt to restore the universe's…"
     },
     {
      "page": "Mayday Parker",
      "left": "…(2015) Web Warriors (2015–2016) Spider-Girls (2018–2019) Spider-",
      "match": "Boy",
      "right": " (2024) References External links Spider-Girl at the Comic Book DB…"
     },
     {
      "page": "Spider-Girl",
      "left": "…Daredevil on top of the Daily Bugle to reclaim the trophy. As Spider-",
      "match": "Boy",
      "right": " is surprised that Spider-Girl knows his true identity and claims that…"
     },
     {
      "page": "Spider-Girl",
      "left": "…tact with. Years prior, Bullseye dispatched Funhouse to attack Spider-",
      "match": "Boy",
      "right": " and Ms. Marvel. After copying the abilities of Ms. Marvel and Stegron…"
     }
    ],
    "Marvel Boy": [
     {
      "page": "Captain Marvel (Marvel Comics)",
      "left": "…Grant Morrison and J.G. Jones, the character first appeared in Marvel ",
      "match": "Boy",
      "right": " #1 (August 2000). As part of the Dark Reign storyline, Noh-Varr joine…"
     },
     {
      "page": "Marvel Boy (Robert Grayson)",
      "left": "…not appear again until What If #9 (June 1978). This version of Marvel ",
      "match": "Boy",
      "right": " was revived within mainstream Marvel continuity, in a 1950s setting,…"
     },
     {
      "page": "Marvel Boy (Robert Grayson)",
      "left": "…ces External links Marvel Boy (Robert Grayson) at Marvel.com Marvel ",
      "match": "Boy",
      "right": " (Robert Grayson) at the Comic Book DB (archived from the original) Ma…"
     },
     {
      "page": "Noh-Varr",
      "left": "…ng Kate Bishop's former boyfriend and teammate, Fuse. In 2020, Marvel ",
      "match": "Boy",
      "right": " was featured as a member of a new Guardians of the Galaxy team alongs…"
     }
    ],
    "Moon-Boy": [
     {
      "page": "Devil Dinosaur",
      "left": "…ike dinosaur. The character and his inseparable ape-like friend, Moon-",
      "match": "Boy",
      "right": ", are natives of \"Dinosaur World,\" a version of Earth in a parallel un…"
     },
     {
      "page": "Devil Dinosaur",
      "left": "…e Fallen Angels to Dinosaur World, the group convinces Devil and Moon-",
      "match": "Boy",
      "right": " to join their team and return with them to Earth-616. During his time…"
     },
     {
      "page": "Devil Dinosaur",
      "left": "…Land The Heroes for Hire mercenaries go on a mission to retrieve Moon-",
      "match": "Boy",
      "right": " from the Savage Land and encounter Devil Dinosaur, who is guarding a…"
     },
     {
      "page": "Devil Dinosaur",
      "left": "…gs to experiment on them. Spider-Man arrives and helps Devil and Moon-",
      "match": "Boy",
      "right": " defeat the cybernetic dinosaurs and rescue the eggs. At the end of th…"
     }
    ],
    "Boy-Thing": [
     {
      "page": "Man-Thing",
      "left": "…H and is imprisoned in a Roxxon facility, but is eventually freed. ",
      "match": "Boy",
      "right": "-Thing Xarus obtains a piece of the original Man-Thing and grows a sim…"
     },
     {
      "page": "Man-Thing",
      "left": "…ece of the original Man-Thing and grows a similar creature called the ",
      "match": "Boy",
      "right": "-Thing. Boy-Thing spends all of his time on Xarus' shoulder, supplying…"
     },
     {
      "page": "Man-Thing",
      "left": "…original Man-Thing and grows a similar creature called the Boy-Thing. ",
      "match": "Boy",
      "right": "-Thing spends all of his time on Xarus' shoulder, supplying him with s…"
     },
     {
      "page": "Man-Thing",
      "left": "…ainst the vampires. After Xarus is killed by Blade, the latter adopts ",
      "match": "Boy",
      "right": "-Thing. Comic book character spin-offs Dr. Barbara \"Bobbi\" Morse was…"
     }
    ]
   }
  },
  "girl": {
   "total": 466,
   "real": 69,
   "name": 394,
   "other": 3,
   "parts": [
    {
     "label": "real",
     "count": 69
    },
    {
     "label": "Spider-Girl",
     "count": 233
    },
    {
     "label": "Moon Girl",
     "count": 39
    },
    {
     "label": "Marvel Girl",
     "count": 37
    },
    {
     "label": "Thor Girl",
     "count": 27
    },
    {
     "label": "other names",
     "count": 58
    },
    {
     "label": "other caps",
     "count": 3
    }
   ],
   "dots": [
    {
     "label": "real",
     "n": 7
    },
    {
     "label": "Spider-Girl",
     "n": 23
    },
    {
     "label": "Moon Girl",
     "n": 4
    },
    {
     "label": "Marvel Girl",
     "n": 4
    },
    {
     "label": "Thor Girl",
     "n": 3
    },
    {
     "label": "other names",
     "n": 6
    },
    {
     "label": "other caps",
     "n": 0
    }
   ],
   "examples": {
    "Moon Girl": [
     {
      "page": "Adam Warlock",
      "left": "…of Man-Thing and Fin Fang Foom), Moon Squirrel (a combination of Moon ",
      "match": "Girl",
      "right": " and Squirrel Girl) and Tippysaurus (a combination of Tippy-Toe and De…"
     },
     {
      "page": "Devil Dinosaur",
      "left": "…nts whilst Lunella rampages through the city. Devil Dinosaur and Moon ",
      "match": "Girl",
      "right": "'s next opponent came in the form of Kid Kree - a misunderstood Kree b…"
     },
     {
      "page": "Devil Dinosaur",
      "left": "…arrive at the Sanctum Sanctorum and are found by Doctor Strange. Moon ",
      "match": "Girl",
      "right": " and two of her classmates are attacked by Doctor Doom and his Doombot…"
     },
     {
      "page": "Devil Dinosaur",
      "left": "…Moon Girl and Devil have switched brains just in time, enabling Moon ",
      "match": "Girl",
      "right": " to lead the Warriors to an Inhuman prison camp. There, the Warriors p…"
     }
    ],
    "real": [
     {
      "page": "Alex Wilder",
      "left": "…a secret crime ring called \"the Pride\") murder of an innocent teenage ",
      "match": "girl",
      "right": ", Alex organizes the mass escape from their parents. Alex then obtains…"
     },
     {
      "page": "Cloak and Dagger (characters)",
      "left": "…stakenly believed he had just robbed a store. Tandy was a 16-year-old ",
      "match": "girl",
      "right": " from a privileged upbringing (born in Shaker Heights, Ohio) who ran a…"
     },
     {
      "page": "Gwenpool",
      "left": "…a giant purple dog monster for a loyal pet. Terrible Eye: Gwen's only ",
      "match": "girl",
      "right": " friend on the merc crew they were all forcibly forced to join she has…"
     },
     {
      "page": "Jack Monroe (character)",
      "left": "…g solo again, Monroe becomes an urban vigilante. He kidnaps an infant ",
      "match": "girl",
      "right": " from her drug addicted mother, naming the infant \"Bucky\". The Commiss…"
     }
    ],
    "Spider-Girl": [
     {
      "page": "Anya Corazon",
      "left": "…haracter to adopt the identity Araña (Spider), before becoming Spider-",
      "match": "Girl",
      "right": " (Young Allies #5, October 2010). She is the third Spider-Girl publish…"
     },
     {
      "page": "Anya Corazon",
      "left": "…st of the Young Allies arrive. Spider-Girl Anya accepts the \"Spider-",
      "match": "Girl",
      "right": "\" moniker and begins operating solo, although she frequently interacts…"
     },
     {
      "page": "Anya Corazon",
      "left": "…und these to be harder to use since losing her abilities. As Spider-",
      "match": "Girl",
      "right": " Writer Paul Tobin stated In an interview with Newsarama that as Spide…"
     },
     {
      "page": "Anya Corazon",
      "left": "…ins her in becoming a superhero. Video games Anya Corazon as Spider-",
      "match": "Girl",
      "right": " appears as a card in Marvel War of Heroes. Anya Corazon as Araña and…"
     }
    ],
    "Marvel Girl": [
     {
      "page": "Betsy Braddock",
      "left": "…ve been greatly enhanced. At the time of Betsy's resurrection, Marvel ",
      "match": "Girl",
      "right": " claimed that Betsy's telekinesis was on a level even she could not ma…"
     },
     {
      "page": "Jean Grey",
      "left": "…y Cassandra Nova. The adult Jean returns to using her original Marvel ",
      "match": "Girl",
      "right": " codename and wears her second green-and-yellow Marvel Girl costume. S…"
     },
     {
      "page": "Jean Grey",
      "left": "…rey) at Marvel.com Jean Grey (Age of Apocalypse) at Marvel.com Marvel ",
      "match": "Girl",
      "right": " (Ultimate) at Marvel.com Jean Grey (Earth-9575) at Marvel.com…"
     },
     {
      "page": "Rachel Summers",
      "left": "…ys of great power. During her 2000s Uncanny X-Men appearances, Marvel ",
      "match": "Girl",
      "right": " also exhibited a Phoenix emblem over her left eye whenever she demons…"
     }
    ],
    "Thor Girl": [
     {
      "page": "Debrii",
      "left": "…ker of Stone. She and Rage help the team in their battle against Thor ",
      "match": "Girl",
      "right": ", who had recovered her powers. Powers and abilities Debrii is descr…"
     },
     {
      "page": "Thor Girl",
      "left": "…e transforms herself into an Asgardian goddess, taking the name \"Thor ",
      "match": "Girl",
      "right": "\" and the human identity of Tara. In a later battle against Surtur, Th…"
     },
     {
      "page": "Thor Girl",
      "left": "…lp the Avengers in battle against the Hulk and his Warbound, and Thor ",
      "match": "Girl",
      "right": " is among the trainees who sides with Rage. Easily defeated, Thor Girl…"
     },
     {
      "page": "Thor Girl",
      "left": "…aced by Skrulls. Fear Itself During the Fear Itself storyline, Thor ",
      "match": "Girl",
      "right": " joins the New Initiative under Prodigy's leadership. She is quite con…"
     }
    ]
   }
  }
 },
 "she": {
  "tokenizer_total": 3840,
  "glued": 433,
  "glued_forms": [
   [
    "She-Hulk",
    404
   ],
   [
    "She-Venom",
    14
   ],
   [
    "She-Hulks",
    6
   ],
   [
    "She-Devil",
    3
   ],
   [
    "She-Thing",
    2
   ]
  ],
  "next": [
   [
    "is",
    501
   ],
   [
    "hulk",
    406
   ],
   [
    "was",
    335
   ],
   [
    "has",
    197
   ],
   [
    "can",
    120
   ],
   [
    "also",
    99
   ],
   [
    "had",
    68
   ],
   [
    "and",
    64
   ]
  ]
 },
 "he_total": 6380
};
