"""Rebuild the reciprocity view and its matched undirected-connection baseline.
Run from any directory: python showcases/week-01-network-questions/claude/build_reciprocity.py
Requires NetworkX and NumPy. No network requests.
"""
import csv
import json
import random
from pathlib import Path
import networkx as nx

BASE = Path(__file__).resolve().parent
ROOT = BASE.parents[2]

def rows(path):
    with path.open(encoding='utf-8') as handle:
        return list(csv.reader((line for line in handle if not line.startswith('#')), delimiter='\t'))

roster = rows(ROOT / 'data/week1/week1_nodes.tsv')[1:]
names = {row[0]: row[1] for row in roster}
graph = nx.DiGraph()
graph.add_nodes_from(names)
graph.add_edges_from(rows(ROOT / 'data/week1/week1_edges.tsv'))
assert (len(graph), graph.number_of_edges()) == (303, 1784)
assert nx.number_of_selfloops(graph) == 0
undirected = graph.to_undirected()
mutual = nx.Graph()
mutual.add_nodes_from(graph)
mutual.add_edges_from((a, b) for a, b in undirected.edges() if graph.has_edge(a,b) and graph.has_edge(b,a))

def metrics(g):
    components = sorted(nx.connected_components(g), key=len, reverse=True)
    return {'largest': len(components[0]), 'isolates': len(list(nx.isolates(g))), 'components': len(components)}

# Sample connections, not directed arcs: weak connectivity depends on whether
# either direction exists. Both observed and random graphs retain 350 pairs.
rng = random.Random(2026)
pairs = sorted(tuple(sorted(edge)) for edge in undirected.edges())
trials = []
for _ in range(500):
    trial = nx.Graph()
    trial.add_nodes_from(graph)
    trial.add_edges_from(rng.sample(pairs, mutual.number_of_edges()))
    trials.append(metrics(trial))

components = sorted(nx.connected_components(undirected), key=len, reverse=True)
giant = components[0]
layout = nx.spring_layout(undirected.subgraph(sorted(giant)), seed=42, iterations=180)
xs = [p[0] for p in layout.values()]; ys = [p[1] for p in layout.values()]
positions = {a: [45+680*(p[0]-min(xs))/(max(xs)-min(xs)), 55+440*(p[1]-min(ys))/(max(ys)-min(ys))] for a,p in layout.items()}
import math
island = sorted(components[1])
for i,a in enumerate(island):
    angle = i*2*math.pi/len(island)
    positions[a] = [830+48*math.cos(angle), 205+48*math.sin(angle)]
for i,a in enumerate(sorted(nx.isolates(undirected))):
    positions[a] = [782+(i%5)*23, 350+(i//5)*25]
ids = list(graph); index = {a:i for i,a in enumerate(ids)}
data = {
 'nodes': [{'id':a, 'name':names[a], 'x':round(positions[a][0],2), 'y':round(positions[a][1],2),
            'incoming':graph.in_degree(a), 'outgoing':graph.out_degree(a), 'mutual':mutual.degree(a),
            'isolated':undirected.degree(a)==0} for a in ids],
 'edges': [{'a':index[a], 'b':index[b], 'mutual':mutual.has_edge(a,b)} for a,b in pairs],
 'full':metrics(undirected), 'reciprocal':metrics(mutual), 'trials':trials,
 'connections':undirected.number_of_edges(), 'retained':mutual.number_of_edges(), 'seed':2026,
}
(BASE/'assets/reciprocity-data.js').write_text('/* Generated by build_reciprocity.py. */\nconst reciprocityData = '+json.dumps(data,separators=(',',':'))+';\n')
print(json.dumps({k:data[k] for k in ['full','reciprocal','connections','retained']}))
for key in ['largest','isolates']:
    values=sorted(t[key] for t in trials)
    print(key, 'random median', (values[249]+values[250])/2, 'central 95% empirical range', values[12],values[487], 'min/max', values[0],values[-1])
